title: Yutian Tang's blog
author: Yutian Tang
description: Yutian Tang's blog

highlighter: null
permalink: /:title

url: http://blog.chrisyttang.org
baseurl: http://blog.chrisyttang.org

# Custom options:
# color_scheme: azul|ruby|amber|avocado
# color_scheme: avocado
